<a href="https://colab.research.google.com/github/Swethaa-sri/Data_Science/blob/main/Numpy_task_d15.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


##Numpy

#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [ ]:
np.__version__

'1.19.5'

In [ ]:
np.show_config()

#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [ ]:
x = np.zeros(10)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [ ]:
x = np.array([1,2,3,4])
x.size*x.itemsize

32

#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [ ]:
np.info(np.add)

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [ ]:
arry = np.zeros(10)
arry[4] = 1
print(arry)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [ ]:
x = np.arange(10,50)
print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [ ]:
x = np.arange(10,50)
x1 = x[::-1]
print(x1)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [ ]:
s = np.arange(0,9)
s1 = s.reshape(3,3)
print(s1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [ ]:
x1 = np.nonzero([1,2,0,0,4,0])
print(x1)

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [ ]:
y = np.eye(3)
print(y)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [ ]:
x = np.random.random((3,3,3))
print(x)

[[[0.10343363 0.51560681 0.5885137 ]
  [0.14552588 0.80182848 0.29164881]
  [0.48393333 0.6605687  0.48210894]]

 [[0.11851736 0.44463556 0.30381728]
  [0.21275939 0.85889721 0.98997758]
  [0.97676914 0.48373531 0.89180619]]

 [[0.57216778 0.35237665 0.66242158]
  [0.2683399  0.12394111 0.43532405]
  [0.10156025 0.79169978 0.16899326]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [ ]:
x = np.random.random((10,10))
x_min, x_max = x.min(), x.max()
print(x_min, x_max)

0.0008846918634717316 0.9717598067615301


#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [ ]:
x = np.random.random(30)
x_mean = x.mean()
print(x_mean)


0.5528116252460397


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [ ]:
x = np.ones((5,5))
x[1:-1,1:-1] = 0
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [ ]:
x = np.arange(1,13).reshape(3,4)
x1 = np.pad(x,pad_width=1, mode='constant',constant_values = 0 )
x1

array([[ 0,  0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4,  0],
       [ 0,  5,  6,  7,  8,  0],
       [ 0,  9, 10, 11, 12,  0],
       [ 0,  0,  0,  0,  0,  0]])

#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [ ]:
print(0*np.nan)

nan


In [ ]:
print(np.nan == np.nan)

False


In [ ]:
print(np.inf > np.nan)

False


In [ ]:
print(np.nan - np.nan)

nan


In [ ]:
print(0.3 == 3*0.1)

False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [ ]:

z1 = np.diag(np.arange(1,5),k=-1)
z1

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [ ]:
z = np.zeros((8,8), dtype = int)
z[1::2,::2] = 1
z[::2,1::2] = 1
z

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [ ]:
x = np.unravel_index(100,(6,7,8))
x

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [ ]:
x = np.array([[0,1],[0,1]])
x1 = np.tile(x,(4,4))
x1

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1]])

#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [ ]:
x = np.random.random((5,5))
x_min, x_max = x.min(),x.max()
x1 = (x - x_min)/(x_max - x_min)
x1

array([[0.09973542, 0.71056906, 0.84404606, 0.52203078, 0.27749564],
       [0.99554733, 0.36206616, 0.68084137, 0.        , 0.43621798],
       [0.78184395, 0.60616953, 0.95976539, 0.39088577, 0.10962162],
       [0.7648795 , 0.71016827, 0.30811235, 0.80804221, 0.07698631],
       [0.32630523, 0.39789248, 0.37940998, 1.        , 0.83860649]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [ ]:
RGBA = np.dtype([('r',np.uint8),('g',np.uint8),('b',np.uint8),('a',np.uint8)])
#color = np.array((1,2,3,4),dtype = RGBA)
#print(color['red'])
#type(color)
RGBA

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [ ]:
arr1 = np.random.random((5,3))
arr2 = np.random.random((3,2))
arr_dot = np.dot(arr1,arr2)
print(arr_dot)

[[1.06295312 0.67447513]
 [0.50260965 0.32203313]
 [0.22487228 0.09139017]
 [0.8774262  0.60212616]
 [0.795056   0.53399862]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [ ]:
x = np.arange(16)
x[(x > 3) & (x <= 8)] *= -1
x

array([ 0,  1,  2,  3, -4, -5, -6, -7, -8,  9, 10, 11, 12, 13, 14, 15])

#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
print(sum(range(5),-1))

10


In [ ]:
from numpy import *
print(sum(range(5),-1)) 

10


In [ ]:
np.sum(range(5),-1)

10

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
z = np.arange(9).reshape(3,3)
z

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
z**z

array([[       1,        1,        4],
       [      27,      256,     3125],
       [   46656,   823543, 16777216]])

In [ ]:
z1 = 2<<z>>2
z1


array([[  0,   1,   2],
       [  4,   8,  16],
       [ 32,  64, 128]])

In [ ]:
print(z <- z)

[[False False False]
 [False False False]
 [False False False]]


In [ ]:
print(1j*z)

[[0.+0.j 0.+1.j 0.+2.j]
 [0.+3.j 0.+4.j 0.+5.j]
 [0.+6.j 0.+7.j 0.+8.j]]


In [ ]:
print(z/1/1)

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


In [ ]:
print(z<z>z)

ValueError: ignored

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
s = np.array(0)/np.array(0)
print(s)

nan


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


In [ ]:
s = np.array(0)//np.array(0)
print(s)

0


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


In [ ]:
s = np.array([np.nan]).astype(int).astype(float)
print(s)

[-9.22337204e+18]


#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [ ]:
z = np.random.uniform(-10,+10,10)
print(z)
print(np.copysign(np.ceil(np.abs(z)),z))

[ 5.26506109  5.38563753  5.62070649 -7.59616441 -1.11380246 -9.47395911
 -9.51332399  9.09614252 -6.99536274  6.41583352]
[  6.   6.   6.  -8.  -2. -10. -10.  10.  -7.   7.]


#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [ ]:
x1 = np.random.randint(0,5,5)
x2 = np.random.randint(0,5,5)
print('x1  :',x1)
print('x2  :',x2)
print('common : ',np.intersect1d(x1,x2))

x1  : [3 3 0 2 2]
x2  : [4 1 1 2 4]
common :  [2]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [ ]:
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

# Equivalently with a context manager
with np.errstate(all="ignore"):
    np.arange(3) / 0


#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
print(np.sqrt(-1))

nan


In [ ]:
print(np.emath.sqrt(-1))

1j


In [ ]:
print(np.sqrt(-1) == np.emath.sqrt(-1))

False


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [ ]:
yesterday = np.datetime64('today','D')- np.timedelta64(1,'D')
today = np.datetime64('today','D')
tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')

print('yesterday :', yesterday)
print('today :', today)
print('tomorrow :', tomorrow)

yesterday : 2021-12-27
today : 2021-12-28
tomorrow : 2021-12-29


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [ ]:
dates_july = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(dates_july)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [ ]:
a = np.ones(3)*1
b = np.ones(3)*2

print(a)
print(b)
np.add(a,b, out = b)
np.divide(a,2, out = a)
np.negative(a, out = a)
np.multiply(b,a, out = a)





[1. 1. 1.]
[2. 2. 2.]


array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [ ]:
x = np.random.uniform(1,10,10)
print(x)

#x_% = x - x%1
print('% :', x - x%1)

x_floor = np.floor(x)
print('np.floor :', x_floor)

x_ceil = np.ceil(x)-1
print('x_ceil :', x_ceil)

x_astype = x.astype(int)
print('int :', x_astype)

x_trunc = np.trunc(x)
print('x_trunc :', x_trunc)


[6.65292193 9.10730471 7.45207463 6.28123886 2.24039417 5.65618849
 7.49675484 2.19487857 4.45216792 2.09163362]
% : [6. 9. 7. 6. 2. 5. 7. 2. 4. 2.]
np.floor : [6. 9. 7. 6. 2. 5. 7. 2. 4. 2.]
x_ceil : [6. 9. 7. 6. 2. 5. 7. 2. 4. 2.]
int : [6 9 7 6 2 5 7 2 4 2]
x_trunc : [6. 9. 7. 6. 2. 5. 7. 2. 4. 2.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [ ]:
z = np.zeros((5,5))
z += np.arange(5)
print(z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [ ]:
def generator():
  for i in range(10):
    yield i

x = np.fromiter(generator(),dtype = int, count = -1)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [ ]:
x = np.linspace(start = 0, stop = 1,endpoint=False,num=11)[1:]
print(x)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [ ]:
x = np.random.random(10)
x.sort()
print(x)

[0.34307394 0.36058084 0.41096463 0.54489764 0.55238627 0.62327874
 0.76582899 0.83300337 0.87506015 0.90019878]


#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [ ]:
x = np.arange(5)
print(x)
print('sum_np.add.reduce :', np.add.reduce(x))

[0 1 2 3 4]
sum_np.add.reduce : 10


#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [ ]:
a = np.random.randint(0,5,5)
b = np.random.randint(0,5,5)
print(a)
print(b)
equal = np.allclose(a,b)   
print('allclose :', equal)
equal_1 = np.array_equal(a,b)
print('array_equal :', equal_1)

[3 4 0 0 0]
[0 1 3 3 4]
allclose : False
array_equal : False


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [ ]:
x = np.ones(10)
print(x)
x.flags.writeable = False
x[3] = 2
print(x)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


ValueError: ignored

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [ ]:
a = np.random.random((10,2))

x , y = a[:,0],a[:,1]
print('cartesian coordinates  :','\n')
print('x    : ',x,'\n')
print('y    :',y,'\n')
print('polar coordinates  :','\n')
r = np.sqrt(x**2 + y**2)
t = np.arctan2(x,y)
print('r      :',r,'\n')
print('t      :', t,'\n')

cartesian coordinates  : 

x    :  [0.87487275 0.51461812 0.97826999 0.16969221 0.10131214 0.53397596
 0.02557449 0.6301806  0.54423565 0.40222606] 

y    : [0.35007801 0.38702577 0.90727328 0.17195791 0.70975084 0.03698967
 0.47498453 0.85145921 0.47565267 0.72457556] 

polar coordinates  : 

r      : [0.94231467 0.64391051 1.33422523 0.24158843 0.71694519 0.53525561
 0.47567253 1.05929711 0.72279866 0.82873129] 

t      : [1.19016293 0.92597556 0.82303357 0.77876664 0.14178544 1.50163465
 0.05379085 0.63714681 0.85254265 0.50676527] 



#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [ ]:
x = np.random.random(10)
x[x.argmax()]=0
print(x)

[0.80003461 0.         0.74566755 0.90481392 0.42267744 0.00320815
 0.98863528 0.94182868 0.89220411 0.1893303 ]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [ ]:
z = np.zeros((5,5),[('x',float),('y',float)])
z['x'],z['y'] = np.meshgrid(np.linspace(0,1,5),(np.linspace(0,1,5)))
print(z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [ ]:
x = np.arange(8)
y = x + 0.5
c = 1.0/np.subtract.outer(x,y)
print(np.linalg.det(c))

3638.1636371179666


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [ ]:
for dtype in [np.int8, np.int32, np.int64]:
  print('np.iinfo(dtype).min    :',dtype,np.iinfo(dtype).min)
  print('np.iinfo(dtype).max    :',dtype,np.iinfo(dtype).max)

for dtype in [np.float32, np.float64]:
  print('np.finfo(dtype).min    :',dtype, np.finfo(dtype).min)
  print('np.finfo(dtype).max    :',dtype,np.finfo(dtype).max)
  print('np.finfo(dtype)eps     :',dtype,np.finfo(dtype).eps)  


np.iinfo(dtype).min    : <class 'numpy.int8'> -128
np.iinfo(dtype).max    : <class 'numpy.int8'> 127
np.iinfo(dtype).min    : <class 'numpy.int32'> -2147483648
np.iinfo(dtype).max    : <class 'numpy.int32'> 2147483647
np.iinfo(dtype).min    : <class 'numpy.int64'> -9223372036854775808
np.iinfo(dtype).max    : <class 'numpy.int64'> 9223372036854775807
np.finfo(dtype).min    : <class 'numpy.float32'> -3.4028235e+38
np.finfo(dtype).max    : <class 'numpy.float32'> 3.4028235e+38
np.finfo(dtype)eps     : <class 'numpy.float32'> 1.1920929e-07
np.finfo(dtype).min    : <class 'numpy.float64'> -1.7976931348623157e+308
np.finfo(dtype).max    : <class 'numpy.float64'> 1.7976931348623157e+308
np.finfo(dtype)eps     : <class 'numpy.float64'> 2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [ ]:
np.set_printoptions(threshold=np.inf, linewidth=np.nan)
z = np.ones((5,5))
print(z)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [ ]:
x = np.random.random(10)
v = np.random.uniform(0,10)
print('x',x)
print('v',v)
z = np.abs(x-v).argmin()
print('z :',z)
print('closest  :',x[z])


x [0.47971905 0.61050267 0.7125133  0.07850128 0.66585086 0.84789567 0.00195667 0.1423454  0.30387535 0.65668999]
v 2.8645868838347677
z : 5
closest  : 0.847895667561219


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [ ]:
a = np.zeros(10,[('position',[('x',float),('y',float)]),
                 ('color',[('r',float),('g',float),('b',float)])])
print(a)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [ ]:
z = np.random.random((10,2))
x,y = np.atleast_2d(z[:,0],z[:,1])
d = np.sqrt((x-x.T)**2 + (y-y.T)**2)

print(d)

[[0.         0.2485448  0.62541564 0.65523766 0.36942996 0.61840501 0.93429598 0.37781475 1.00280585 0.2875958 ]
 [0.2485448  0.         0.70690021 0.71379097 0.20292565 0.68912578 0.86460057 0.35233681 0.9395691  0.42856226]
 [0.62541564 0.70690021 0.         0.06747925 0.59197778 0.03251229 0.52682822 0.37693173 0.56106026 0.34205025]
 [0.65523766 0.71379097 0.06747925 0.         0.58204669 0.04609382 0.45969655 0.37050511 0.49361856 0.37991803]
 [0.36942996 0.20292565 0.59197778 0.58204669 0.         0.56780011 0.66644299 0.21524044 0.74218519 0.40389332]
 [0.61840501 0.68912578 0.03251229 0.04609382 0.56780011 0.         0.49954209 0.3534419  0.53625522 0.33915957]
 [0.93429598 0.86460057 0.52682822 0.45969655 0.66644299 0.49954209 0.         0.55672095 0.07659638 0.73618228]
 [0.37781475 0.35233681 0.37693173 0.37050511 0.21524044 0.3534419  0.55672095 0.         0.62618828 0.24911142]
 [1.00280585 0.9395691  0.56106026 0.49361856 0.74218519 0.53625522 0.07659638 0.62618828 0.    

In [ ]:
z = np.random.random((100,2))
print(z)
x,y = np.atleast_2d(z[:,0],z[:,1])
d = np.sqrt((x-x.T)**2 + (y-y.T)**2)
print(d)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [ ]:
z = np.arange(10, dtype=np.float32)
print(z)
z1 = z.astype(dtype=np.int32, copy = False)
print(z1)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0 1 2 3 4 5 6 7 8 9]


#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
from io import StringIO
s = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n """)
x = np.genfromtxt(s,dtype=np.int,delimiter=',')
print(x)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


In [ ]:
from io import StringIO
s = StringIO()
s.write('''1, 2, 3, 4, 5\n6,  ,  , 7, 8\n,  , 9, 10, 11\n''')
print(s.getvalue())


1, 2, 3, 4, 5
6,  ,  , 7, 8
,  , 9, 10, 11



#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [ ]:
x = np.arange(4).reshape(2,2)
print(x)
print('np.ndenumerate\n')
for index,value in np.ndenumerate(x):
  print(index,value)
print('np.ndindex\n')
for index in np.ndindex(x.shape):
  print(index,x[index])  

[[0 1]
 [2 3]]
np.ndenumerate

(0, 0) 0
(0, 1) 1
(1, 0) 2
(1, 1) 3
np.ndindex

(0, 0) 0
(0, 1) 1
(1, 0) 2
(1, 1) 3


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [ ]:
x,y = np.meshgrid(np.linspace(-1,1,10),np.linspace(-1,1,10))
d = np.sqrt(x*x + y*y)
sigma , mu = 1.0, 0.0
g = np.exp(-((d-mu)**2/(2.0*sigma**2)))
print(g)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818 0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367 0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308 0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022 0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022 0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308 0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367 0.69905581 0.63331324 0.5461

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [ ]:
p = 4
n = 5
x = np.ones((5,5))
np.put(x,np.random.choice(n,p,replace=False),5)
print(x)

[[5. 1. 5. 5. 5.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
p = 4
n = 5
x = np.ones((5,5))
np.put(x,np.random.choice(n*n,p,replace=False),2)
print(x)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 2. 1.]
 [1. 1. 1. 1. 2.]
 [2. 1. 2. 1. 1.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [ ]:
x = np.random.random((5,5))

y = x - x.mean(axis = 1, keepdims=True)
print(y)

[[-0.06669758 -0.27874462  0.30423088 -0.37688742  0.41809874]
 [ 0.05282038  0.27421993  0.0819889  -0.22395724 -0.18507196]
 [-0.09940385 -0.38136997  0.10363208  0.42532674 -0.048185  ]
 [ 0.13951472  0.21032224 -0.1050832  -0.01206944 -0.23268432]
 [ 0.04904593  0.17457592  0.04635421 -0.31795587  0.04797981]]


#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [ ]:
x = np.random.randint(0,9,(3,3))
print(x,'\n')

z = x[:,2]
print('nth column :', z, '\n')

print('sorted by nth column :')
print(x[z.argsort()])

[[2 3 8]
 [8 6 6]
 [5 7 0]] 

nth column : [8 6 0] 

sorted by nth column :
[[5 7 0]
 [8 6 6]
 [2 3 8]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [ ]:
x = np.random.randint(0,10,(2,5))
print(x)
print((~x.any(axis=0)).any())

[[2 9 8 4 2]
 [8 2 7 2 7]]
False


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [ ]:
x = np.arange(10)
print(x)
k = 4.5
m = x.flat[np.abs(x-k).argmin()]
print(m)

[0 1 2 3 4 5 6 7 8 9]
4


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [ ]:
x = np.arange(3).reshape(1,3)
y = np.arange(3).reshape(3,1)

it = np.nditer([x,y,None])
for x,y,z in it:
  z[...] = x+y
print(it.operands[2])  


[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [ ]:
class named(np.ndarray):
  def __new__(cls, array, name = "no name"):
    obj = np.asarray(array).view(cls)
    obj.name = name
    return obj
  def __array_finalize__(self,obj):
    if obj is None:
      return
    self.info = getattr(obj, 'name', 'no name')  

In [ ]:
z = named(np.arange(10), "range_10")
print(z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [ ]:
x = np.ones(10)

y = np.random.randint(0,len(x),20)

x += np.bincount(y,minlength=len(x))
print(x)

[3. 2. 4. 3. 2. 3. 4. 2. 3. 4.]


In [ ]:
np.add.at(x,y,1)
print(x)

[5. 3. 7. 5. 3. 5. 7. 3. 5. 7.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [ ]:
x = [1,2,3,4,5]
i = [3,4,5,9,12]

z = np.bincount(i,x)
print(z)

[0. 0. 0. 1. 2. 3. 0. 0. 0. 4. 0. 0. 5.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [ ]:
w , h = 256 , 256
i = np.random.randint(0,4,(h,w,3)).astype(np.ubyte)
colors = np.unique(i.reshape(-1,3),axis=0)
n = len(colors)
print(n)

64


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [ ]:
A = np.random.randint(0,10,(2,4,3,4))
sum = A.sum(axis=(-2,-1))
print(sum)

[[57 47 46 38]
 [48 62 66 58]]


In [ ]:
sum_1 = A.reshape(A.shape[:-2]+(-1,)).sum(axis=(-1))
print(sum_1)

[[57 47 46 38]
 [48 62 66 58]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [ ]:
D = np.random.uniform(0,1,100)
S =np.random.randint(0,10,100)
D_sums = np.bincount(S, weights = D)
D_counts = np.bincount(S)
D_mean = D_sums / D_counts
print(D_mean)

[0.71007152 0.39292218 0.5606044  0.49624774 0.55211855 0.49748764
 0.45844345 0.5047203  0.34159433 0.39814787]


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [ ]:
a = np.random.uniform(0,10,(3,3))
b = np.random.uniform(0,10,(3,3))
c = np.diag(np.dot(a,b))
print(c)

[80.13080886 96.78277986 39.36651148]


#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [ ]:
v = np.array([1,2,3,4,5])
z = 3
z_v = np.zeros(len(v) + (len(v)-1)*z)
z_v[::z+1] = v
print(z_v)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [ ]:
a = np.ones((5,5,3))
b = 3*np.ones((5,5))
print(a*b[:,:,None])

[[[3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]]

 [[3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]]

 [[3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]]

 [[3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]]

 [[3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [ ]:
a = np.arange(15).reshape(3,5)
print(a,'\n')
a[[1,0]] = a[[0,1]]
print('swapping \n')
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]] 

swapping 

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [ ]:
faces = np.random.randint(0,50,(10,3))
f = np.roll(faces.repeat(2,axis=1),-1,axis=1)
f = f.reshape(len(f)*3,2)
f = np.sort(f,axis=1)
g = f.view(dtype=[('p0',f.dtype),('p1',f.dtype)])
g = np.unique(g)
print(g)


[( 3, 21) ( 3, 33) ( 7, 37) ( 7, 49) ( 9, 13) ( 9, 25) ( 9, 29) ( 9, 37)
 (12, 14) (12, 29) (13, 25) (14, 29) (14, 33) (14, 35) (19, 43) (19, 49)
 (20, 26) (20, 37) (21, 33) (23, 29) (23, 39) (26, 37) (29, 37) (29, 39)
 (33, 35) (36, 40) (36, 43) (37, 49) (40, 43) (43, 49)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [ ]:
c = np.bincount([1,1,2,3,4,4,6])
print(c)
a = np.repeat(np.arange(len(c)),c)
print(a)


[0 2 1 1 2 0 1]
[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [ ]:
def window_avg(a,n=3):
  ret = np.cumsum(a,dtype=float)
  ret[n:] = ret[n:] - ret[:-n]
  return ret[n-1:]/n

x = np.arange(20)
print(x)
y = window_avg(x,n=3)
print(y)  



[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [ ]:
from numpy.lib import stride_tricks

def numpy_stride(a,window):
  shape = (a.size - window + 1,window)
  strides = (a.strides[0],a.strides[0])
  return stride_tricks.as_strided(a, shape = shape, strides = strides)

x = numpy_stride(np.arange(10),3)
x

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6],
       [5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [ ]:
x = np.random.randint(0,10,10)
print(x)
np.logical_not(x, out=x)

[0 0 5 7 6 4 7 7 9 6]


array([1, 1, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
x = np.random.randint(0,10,10)
print(x)
np.negative(x, out = x)

[8 9 3 8 4 2 6 6 3 6]


array([-8, -9, -3, -8, -4, -2, -6, -6, -3, -6])

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [ ]:
def distance(p0 , p1, p):
  t = p1 - p0
  L = (t**2).sum(axis=1)
  u = -((p0[:,0]-p[...,0])*t[:,0] + (p1[:,1]-p[...,1])*t[:,1])/L
  u = u.reshape(len(u),1)
  d = p0 + u*t - p
  return np.sort((d**2).sum(axis=1))
p0 = np.random.uniform(-10,10,(10,2))
p1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10,10,(1,2)) 
print(distance(p0,p1,p))

[  3.98461506   5.43884767  14.62046965  19.71214429  28.05351439
 156.44146273 198.52844884 240.69168525 299.72344204 359.78947626]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [ ]:
def distance(p0,p1,p):
  t = p1 - p0
  L = (t**2).sum(axis=1)
  u = -((p0[:,0]-p[...,0])*t[:,0] + (p1[:,1]-p[...,1])*t[:,1])/L
  u = u.reshape(len(u),1)
  d = p0 + u*t - p
  return np.sort((d**2).sum(axis=1))

p0 = np.random.uniform(-10,10,(10,2))
p1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10,10,(10,2))
print(np.array([distance(p0,p1,p_1) for p_1 in p]))  

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

In [ ]:
a = np.random.randint(0,10,(10,10))
shape = (5,5)
fill = 0
position = (1,1)

r = np.ones(shape, dtype=a.dtype)*fill
p = np.array(list(position)).astype(int)
rs = np.array(list(r.shape)).astype(int)
a_s = np.array(list(a.shape)).astype(int)

r_start = np.zeros((len(shape),)).astype(int)
r_stop = np.array(list(shape)).astype(int)
a_start = p-rs//2
a_stop = (p+rs//2) + rs%2

r_start = (r_start - np.minimum(a_start,0)).tolist()
a_start = (np.maximum(a_start,0)).tolist()
r_stop = np.maximum(r_start,(r_stop - np.maximum(a_stop - a_s,0))).tolist()
a_stop = (np.minimum(a_stop,a_s)).tolist()

x = [slice(start,stop) for start,stop in zip(r_start,r_stop)]
y = [slice(start,stop) for start,stop in zip(a_start,a_stop)]

r[x] = a[y]

print(r,'\n')
print(a)


[[0 0 0 0 0]
 [0 5 6 8 2]
 [0 4 0 6 5]
 [0 0 6 3 6]
 [0 8 4 8 0]] 

[[5 6 8 2 7 5 9 4 8 4]
 [4 0 6 5 1 4 9 9 3 1]
 [0 6 3 6 9 1 5 7 8 5]
 [8 4 8 0 0 0 6 6 8 6]
 [0 4 4 7 2 8 7 9 4 5]
 [3 9 6 9 2 3 5 1 5 0]
 [8 3 2 9 0 1 3 9 5 4]
 [0 5 9 4 0 9 8 8 8 3]
 [9 0 9 5 7 3 3 3 2 1]
 [7 6 2 1 8 3 5 3 4 8]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:24: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [ ]:
from numpy.lib import stride_tricks
a = np.arange(1,15,dtype = np.uint32)
print(a)
r = stride_tricks.as_strided(a,(11,4),(4,4))
print(r)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [ ]:
# svd = singular value decomposition
a = np.random.uniform(0,1,(10,10))
u , s , v = np.linalg.svd(a)
rank = np.sum(s > 1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [ ]:
x = np.random.randint(0,10,10)
print(x)
s = np.bincount(x).argmax()
print(s)

[5 7 4 5 6 1 1 8 7 3]
1


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [ ]:
from numpy.lib import stride_tricks
s = np.random.randint(0,10,(10,10))
n = 3
i = 1 + (s.shape[0]-3)
j = 1 + (s.shape[1]-3)
c = stride_tricks.as_strided(s,shape=(i,j,n,n),strides=s.strides + s.strides)
print(c)

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

In [ ]:
class Symetric(np.ndarray):
  def __setitem__(self,index,value):
    i,j = index
    super(Symetric,self).__setitem__((i,j),value)
    super(Symetric,self).__setitem__((j,i),value)

def symetric(z):
  return np.asarray(z + z.T - np.diag(z.diagonal())).view(Symetric)    

In [ ]:
s = symetric(np.random.randint(0,10,(5,5)))
s[2,3] = 42
print(s)

[[ 7  5  7 10  0]
 [ 5  5 10 13  9]
 [ 7 10  3 42 15]
 [10 13 42  1  2]
 [ 0  9 15  2  2]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [ ]:
p , n  =  5, 5
m = np.ones((p,n,n))
v = np.ones((p,n,1))
s = np.tensordot(m,v, axes = [[0,2],[0,1]])
print(s)

[[25.]
 [25.]
 [25.]
 [25.]
 [25.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [ ]:
x = np.ones((16,16))
k = 4
s = np.add.reduceat(np.add.reduceat(x, np.arange(0, x.shape[0], k), axis = 0) , np.arange(0, x.shape[1], k), axis = 1)
print(x,'\n')
print(s,'\n')

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]] 

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]] 



#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [ ]:
def iterator(x):
  # count neighbors
  n = (x[0:-2,0:-2] + x[0:-2,1:-1] + x[0:-2,2:] + 
       x[1:-1,0:-2]                 +x[1:-1,2:] +
       x[2:  ,0:-2] + x[2: ,1:-1] + x[2: ,2: ])
  
# Apply rules
  birth = (n==3) & (x[1:-1,1:-1]==0)
  survive = ((n==2) | (n==3)) & (x[1:-1,1:-1]==1)
  x[...] = 0
  x[1:-1,1:-1][birth | survive] = 1
  return x

x = np.random.randint(0,2,(50,50))
for i in range(100): x = iterator(x)

#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [ ]:
x = np.arange(1000)
np.random.shuffle(x)
n = 5

print(x[(np.argsort(x))[-n:]])


[995 996 997 998 999]


In [ ]:
print(x[np.argpartition(-x,n)[:n]])

[997 999 998 996 995]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [ ]:
def cartesian(arrays):
  arrays = [np.asarray(a) for a in arrays]
  shape = (len(x) for x in arrays)

  ix = np.indices(shape, dtype = int)
  ix = ix.reshape(len(arrays),-1).T

  for n, arr in enumerate(arrays):
    ix[:,n] = arrays[n][ix[:,n]]
  return ix

print(cartesian(([1,2,3],[4,5],[6,7])))    

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [ ]:
a = np.array([("Hello", 2.5, 3),("World", 3.6, 2)])
r = np.core.records.fromarrays(a.T, names = 'col1, col2, col3', formats = 'S8, f8, i8')

print(r)


[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [ ]:
x = np.random.rand(int(5e7))
s = np.power(x,3)
print(s)

s1 = x*x*x
print(s1)

s3 = np.einsum('i,i,i->i',x,x,x)
print(s3)

[0.01070648 0.35649115 0.00126052 ... 0.54110571 0.20287756 0.00834722]
[0.01070648 0.35649115 0.00126052 ... 0.54110571 0.20287756 0.00834722]
[0.01070648 0.35649115 0.00126052 ... 0.54110571 0.20287756 0.00834722]


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [ ]:
a = np.random.randint(0,5,(3,3))
b = np.random.randint(0,5,(2,2))
print(a,'\n')
print('.......')
print(b,'\n')
c = (a[...,np.newaxis,np.newaxis] == b)
rows = np.where(c.any((3,1)).all(1))[0]
print(rows)

[[4 0 2]
 [1 1 0]
 [2 1 1]] 

.......
[[2 1]
 [0 0]] 

[0 1]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [ ]:
a = np.random.randint(0,10,(10,3))
print(a)
print('............')
e = np.all(a[:,1:] == a[:,:-1], axis = 1)
u = a[~e]
print(u)

[[3 4 7]
 [8 2 0]
 [7 2 5]
 [5 5 5]
 [3 5 8]
 [8 9 1]
 [1 6 2]
 [7 1 8]
 [2 7 4]
 [3 7 0]]
............
[[3 4 7]
 [8 2 0]
 [7 2 5]
 [3 5 8]
 [8 9 1]
 [1 6 2]
 [7 1 8]
 [2 7 4]
 [3 7 0]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [ ]:
i = np.array([0,1,2,3,15,16,32,64,128], dtype = np.uint8)
print(np.unpackbits(i[:,np.newaxis],axis=1))


[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [ ]:
a = np.random.randint(0,2,(6,3))
t = np.ascontiguousarray(a).view(np.dtype((np.void,a.dtype.itemsize * a.shape[1])))
_, idx = np.unique(t, return_index=True)
d = a[idx]
print(a)
print('.....................')
print(d)

[[0 0 1]
 [0 1 0]
 [0 0 1]
 [1 1 1]
 [1 0 1]
 [0 0 0]]
.....................
[[0 0 0]
 [0 0 1]
 [0 1 0]
 [1 0 1]
 [1 1 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [ ]:
a = np.random.randint(0,10,4)
b = np.random.randint(0,10,4)

a1 = np.einsum('i->',a)   # np.sum(a)
a2 = np.einsum('i,i->i',a,b) # a*b
a3 = np.einsum('i,i',a,b) # np.inner(a,b)
a4 = np.einsum('i,j->ij', a,b) # np.outer(a,b)
print('a :',a,'\n')
print('b :',b,'\n')
print('............')
print('np.sum(a)  :',a1)
print('.......')
print('a*b   :',a2)
print('........')
print('np.inner(a,b)  :',a3)
print('........')
print('np.outer(a,b)  :',a4)


a : [3 6 9 3] 

b : [9 9 6 9] 

............
np.sum(a)  : 21
.......
a*b   : [27 54 54 27]
........
np.inner(a,b)  : 162
........
np.outer(a,b)  : [[27 27 18 27]
 [54 54 36 54]
 [81 81 54 81]
 [27 27 18 27]]


#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

In [ ]:
phi = np.arange(0,10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr) # integrate path
r_int = np.linspace(0, r.max(),200)  # regular spaced path
x_int = np.interp(r_int,r,x)  # integrate path
y_int = np.interp(r_int,r,y)




#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [ ]:
x = np.asarray([[1.0, 0.0, 3.0, 8.0],[2.0, 0.0, 1.0, 1.0],[1.5, 2.5, 1.0, 0.0]])
print(x)
print('..........')
n = 4
m =np.logical_and.reduce(np.mod(x,1) == 0, axis = -1)
m &= (x.sum(axis= -1) == n)
print(x[m])

[[1.  0.  3.  8. ]
 [2.  0.  1.  1. ]
 [1.5 2.5 1.  0. ]]
..........
[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [ ]:
x = np.random.randn(100) # random 1d array
n = 1000 # number of bootstrap samples
idx = np.random.randint(0, x.size, (n,x.size))
means = x[idx].mean(axis = 1)
confint = np.percentile(means, [2.5, 97.5])
print(confint) 

[-0.23230763  0.1366793 ]
